---

- name: restart helga service
  service:
    name: helga
    status: restarted

# prevents issues when updating systemd files
- name: reload systemd
  become: yes
  command: systemctl daemon-reload
