---

- name: ensure /var/log/graphite dir exists
  become: true
  file: 
    path: /var/log/graphite 
    state: directory 
    owner: _graphite 
    group: _graphite 
    recurse: yes

- name: install the systemd unit file for graphite
  template: 
    src: systemd/graphite.service.j2 
    dest: /etc/systemd/system/graphite.service
  become: true
  notify:
     - reload systemd

- name: ensure graphite is enabled and running
  become: true
  service: 
    name: graphite 
    state: running 
    enabled: yes
