- project:
    name: ceph-api-nightly
    ceph_branch:
      - master
      - octopus
      - nautilus:
          ceph_build: "export CHECK_MAKEOPTS='-N -Q'; timeout 2h ./run-make-check.sh"
    test_suite:
      - backend:
          test_suite_script: run-backend-api-tests.sh
          test_deps_script: install-backend-api-test-deps.sh
      - e2e:
          test_suite_script: run-frontend-e2e-tests.sh
          test_deps_script: install-e2e-test-deps.sh
    jobs:
      - '{name}-{ceph_branch}-{test_suite}'

- job-template:
    name: '{name}-{ceph_branch}-{test_suite}'
    display-name: '{name}-{ceph_branch}-{test_suite}'
    project-type: freestyle
    defaults: global
    concurrent: true
    node: huge && bionic && x86_64 && !xenial && !trusty
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 300
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph/
      - rebuild:
          auto-rebuild: true
    ceph_build: "export FOR_MAKE_CHECK=1; timeout 2h ./src/script/run-make.sh --cmake-args '-DWITH_TESTS=OFF -DENABLE_GIT_VERSION=OFF'"

    triggers:
      - timed: '@midnight'

    scm:
      - git:
          url: https://github.com/ceph/ceph.git
          branches:
            - '{ceph_branch}'
          browser: auto
          timeout: 20
          skip-tag: true
          shallow-clone: true
          wipe-workspace: true

    builders:
      - shell: "export NPROC=$(nproc); {ceph_build}"
      - shell:
          !include-raw:
            -  ../../../scripts/dashboard/{test_deps_script}
      - shell: |
          export CYPRESS_ARGS="--record --key $CYPRESS_RECORD_KEY --tag $JOB_NAME" COMMIT_INFO_MESSAGE="$JOB_NAME"
          cd src/pybind/mgr/dashboard; timeout 2h ./{test_suite_script}

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: cd-cypress-record-key
              variable: CYPRESS_RECORD_KEY
      - ansicolor

    publishers:
      - email:
          recipients: ceph-qa@ceph.io
