---
- name: ensure database service is up
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: allow users to connect locally
  become: yes
  lineinfile:
     # TODO: should not hardcode that version
     dest: /etc/postgresql/9.5/main/pg_hba.conf
     regexp: '^host\s+all\s+all\s+127.0.0.1/32'
     line: 'host    all             all             127.0.0.1/32            md5'
     backrefs: yes
  register: pg_hba_conf

- service:
    name: postgresql
    state: restarted
  become: true
  when: pg_hba_conf.changed

- name: make {{ app_name }} user
  postgresql_user:
    name: "{{ app_name }}"
    password: "{{ db_password.stdout }}"
    role_attr_flags: SUPERUSER
    login_user: postgres
  become_user: postgres
  become: yes

- name: Make {{ app_name }} database
  postgresql_db:
    name: "{{ app_name }}"
    owner: "{{ app_name }}"
    state: present
    login_user: postgres
  become_user: postgres
  become: yes

- name: ensure database service is up
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes
