---

- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart app
  become: true
  service: 
    name: graphite 
    state: restarted 
    enabled: yes

- name: restart carbon
  service:
    name: carbon-cache
    state: restarted
    enabled: yes
  become: yes

