---
- name: update apt cache
  apt:
    update_cache: yes
  become: yes

- name: set postgresql version on trusty
  set_fact:
      postgresql_version: "9.3"
  when: ansible_distribution_release == "trusty"

- name: set postgresql version on xenial
  set_fact:
      postgresql_version: "9.5"
  when: ansible_distribution_release == "xenial"

- name: install postgresql requirements
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    - postgresql
    - postgresql-common
    - postgresql-contrib
    - "postgresql-server-dev-{{ postgresql_version }}"
    - python-psycopg2
  tags:
    - packages

- name: ensure database service is up
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: allow users to connect locally
  become: yes
  lineinfile:
     dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
     # allow all ipv4 local connections without a password
     line: 'host    all             all             0.0.0.0/0            trust'
  register: pg_hba_conf

- name: make jenkins-build user
  postgresql_user:
    name: "jenkins-build"
    password: "secret"
    role_attr_flags: SUPERUSER
    login_user: postgres
  become_user: postgres
  become: yes

- service:
    name: postgresql
    state: restarted
  become: true
