- project:
    name: ceph-ansible-nightly-stable3.2
    release:
      - luminous
    distribution:
      - centos
    deployment:
      - container
      - non_container
    scenario:
      - all_daemons
      - collocation
      - update
      - lvm_osds
      - shrink_mon
      - shrink_osd
      - lvm_batch
      - add_osds
      - rgw_multisite
      - purge
      - ooo_collocation
      - switch_to_containers
    ceph_ansible_branch:
      - stable-3.2
    jobs:
        - 'ceph-ansible-nightly-{release}-{distribution}-{deployment}-{ceph_ansible_branch}-{scenario}'
    exclude:
      - deployment: non_container
        scenario: ooo_collocation
      - deployment: container
        scenario: switch_to_containers

- project:
    name: ceph-ansible-nightly-stable4.0
    release:
      - nautilus
    distribution:
      - centos
    deployment:
      - container
      - non_container
    scenario:
      - all_daemons
      - collocation
      - update
      - lvm_osds
      - shrink_mon
      - shrink_osd_multiple
      - shrink_osd_single
      - lvm_batch
      - add_osds
      - rgw_multisite
      - purge
      - lvm_auto_discovery
      - ooo_collocation
      - switch_to_containers
    ceph_ansible_branch:
      - stable-4.0
    jobs:
        - 'ceph-ansible-nightly-{release}-{distribution}-{deployment}-{ceph_ansible_branch}-{scenario}'
    exclude:
      - deployment: non_container
        scenario: ooo_collocation
      - deployment: container
        scenario: switch_to_containers

- project:
    name: ceph-ansible-nightly-stable5.0
    release:
      - octopus
    distribution:
      - centos
    deployment:
      - container
      - non_container
    scenario:
      - all_daemons
      - collocation
      - update
      - lvm_osds
      - shrink_mon
      - shrink_osd_multiple
      - shrink_osd_single
      - lvm_batch
      - add_osds
      - rgw_multisite
      - purge
      - lvm_auto_discovery
      - ooo_collocation
      - switch_to_containers
    ceph_ansible_branch:
      - stable-5.0
    jobs:
        - 'ceph-ansible-nightly-{release}-{distribution}-{deployment}-{ceph_ansible_branch}-{scenario}'
    exclude:
      - deployment: non_container
        scenario: ooo_collocation
      - deployment: container
        scenario: switch_to_containers

- job-template:
    name: 'ceph-ansible-nightly-{release}-{distribution}-{deployment}-{ceph_ansible_branch}-{scenario}'
    node: vagrant&&libvirt&&centos7
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Nightly [{release}-{distribution}-{deployment}-{ceph_ansible_branch}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
      - build-discarder:
          days-to-keep: 90
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: CEPH_ANSIBLE_BRANCH
          description: "The ceph-ansible branch (or tag) to test"
          default: "{ceph_ansible_branch}"
      - string:
          name: CEPH_DOCKER_IMAGE_TAG
          description: "The ceph-container image tag to use"
          default: ""

    triggers:
      - timed: '@daily'

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - $CEPH_ANSIBLE_BRANCH
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - inject:
          properties-content: |
            RELEASE={release}
            DISTRIBUTION={distribution}
            DEPLOYMENT={deployment}
            CEPH_ANSIBLE_BRANCH={ceph_ansible_branch}
            SCENARIO={scenario}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-escape:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - username-password-separated:
              credential-id: ceph-ansible-upstream-ci
              username: DOCKER_HUB_USERNAME
              password: DOCKER_HUB_PASSWORD
