---
## This playbook force reinstalls vagrant and the vagrant-libvirt plugin on CentOS 8.  It assumes:
##   - You've run slave.yml
##   - You have `html2text` installed locally and it's in your path
##
## Example:
## ansible-playbook -vvv centos8-vagrant.yml --limit braggi21*

- hosts: all
  become: true
  user: ubuntu
  vars:
    jenkins_user: jenkins-build
    hackery_packages:
      - gcc
      - libguestfs-tools-c
      - libvirt
      - libvirt-devel
      - libxml2-devel
      - libxslt-devel
      - make
      - ruby-devel

  tasks:
    - name: Get the latest vagrant version
      shell: curl -s https://releases.hashicorp.com/vagrant/ | html2text | grep '*' | grep -v '../' | head -n 1 | cut -d '_' -f2
      delegate_to: localhost
      register: latest_vagrant_version

    - name: Set the latest vagrant version URL
      set_fact:
        latest_vagrant_url: "https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_x86_64.rpm"
        # Latest vagrant version sometimes has issue.  Pinning to 2.2.10 for now.
        # latest_vagrant_url: "https://releases.hashicorp.com/vagrant/{{ latest_vagrant_version.stdout }}/vagrant_{{ latest_vagrant_version.stdout }}_x86_64.rpm"

    ## Wipe out vagrant stuff
    # From https://github.com/vagrant-libvirt/vagrant-libvirt/issues/943#issuecomment-463678158
    - name: Wipe out vagrant stuff
      shell: |
        rvm implode
        sudo gem uninstall --all
      become_user: "{{ jenkins_user }}"
      ignore_errors: true

    - name: Wipe out more vagrant stuff
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/home/{{ jenkins_user }}/.vagrant.d/gems"
        - "/home/{{ jenkins_user }}/.vagrant.d/plugins.json"

    - name: Remove vagrant
      dnf:
        name: vagrant
        state: absent

    - name: Install packages
      dnf:
        name: "{{ hackery_packages + [ latest_vagrant_url ] }}"
        state: present
        disable_gpg_check: yes

    # https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1127#issuecomment-713651332
    # https://github.com/hashicorp/vagrant/issues/11020#issuecomment-633802295
    - name: Library hackery
      shell: |
        cd $(mktemp -d)
        wget https://vault.centos.org/8.4.2105/BaseOS/Source/SPackages/krb5-1.18.2-8.el8.src.rpm
        rpm2cpio krb5-1.18.2-8.el8.src.rpm | cpio -imdV
        tar xf krb5-1.18.2.tar.gz; cd krb5-1.18.2/src
        LDFLAGS='-L/opt/vagrant/embedded/' ./configure
        make
        sudo cp lib/libk5crypto.* /opt/vagrant/embedded/lib/
# This was required for vagrant-libvirt version 0.5.3.  That version was giving us a lot of trouble
# so we've pinned vagrant-libvirt to a known good version, 0.3.0.
# Just saving this in case we want in in the future.
#        wget https://vault.centos.org/8.4.2105/BaseOS/Source/SPackages/libssh-0.9.4-2.el8.src.rpm
#        rpm2cpio libssh-0.9.4-2.el8.src.rpm | cpio -imdV
#        tar xf libssh-0.9.4.tar.xz
#        mkdir build
#        cd build
#        cmake ../libssh-0.9.4 -DOPENSSL_ROOT_DIR=/opt/vagrant/embedded/
#        make
#        cp lib/libssh* /opt/vagrant/embedded/lib64

    # https://github.com/vagrant-libvirt/vagrant-libvirt/issues/943#issuecomment-479360033
    - name: Install the vagrant-libvirt plugin (EL)
      shell: vagrant plugin install vagrant-libvirt --plugin-version 0.3.0
      become_user: "{{ jenkins_user }}"
      environment:
        CONFIGURE_ARGS: 'with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib'
        GEM_HOME: '~/.vagrant.d/gems'
        GEM_PATH: '$GEM_HOME:/opt/vagrant/embedded/gems'
