# This playbook requires that you install the roles defined
# in ./requirements/sensu-requirements.yml. Do this by running:
#
#     ansible-galaxy install -r requirements/sensu-requirements.yml
#
- hosts: sensu-server
  become: true
  vars_files:
    - vars/sensu-vars.yml
  roles:
    - role: Mayeu.RabbitMQ
      rabbitmq_vhost_definitions:
          - name: "/sensu"
      rabbitmq_users_definitions:
          - vhost: "/sensu"
            user: sensu
            password: secret
            configure_priv: ".*"
            read_priv: ".*"
            write_priv: ".*"
      rabbitmq_ssl: false
    - redis
    - role: Mayeu.sensu
      sensu_server_rabbitmq_port: 5672
      sensu_server_api_password: secret
      sensu_server_rabbitmq_password: secret
      sensu_server_dashboard_password: secret
      sensu_client_subscription_names:
        - common
        - rabbitmq
      # these are custom settings for this client
      sensu_settings:
        # used in the rabbitmq-alive check
        rabbitmq:
          user: sensu
          password: secret
          # we need to escape the / in /sensu
          vhost: "%2Fsensu"

- hosts: sensu-clients
  become: true
  vars_files:
    - vars/sensu-vars.yml
  roles:
    - role: Mayeu.sensu
      sensu_server_rabbitmq_hostname: "{{ rabbitmq_client_address|mandatory }}"
      sensu_server_rabbitmq_port: 5672
      sensu_server_rabbitmq_password: secret
      sensu_install_server: false
      sensu_install_uchiwa: false
      # sensu_client_subscription_names need to be defined in a hosts_var file
      # relative to your inventory
